const templates = [
    { filename: "1.html", name: "1" },
    { filename: "2.html", name: "2" },
    { filename: "3.html", name: "3" },
    { filename: "4.html", name: "4" },
    { filename: "5.html", name: "5" },
    { filename: "6.html", name: "6" },
    { filename: "7.html", name: "7" },
    { filename: "8.html", name: "8" },
    { filename: "9.html", name: "9" },
    { filename: "10.html", name: "10" },
    { filename: "11.html", name: "11" },
    { filename: "12.html", name: "12" },
    { filename: "13.html", name: "13" },
    { filename: "14.html", name: "14" },
    { filename: "15.html", name: "15" },
    { filename: "16.html", name: "16" },
    { filename: "17.html", name: "17" },
    { filename: "18.html", name: "18" },
    { filename: "19.html", name: "19" },
    { filename: "20.html", name: "20" },
    { filename: "index.html", name: "Index" },
    { filename: "main_v1.html", name: "Main V1" }
];
